In [1]:
import numpy as np

# 1
# a
array_a = np.arange(1, 11)
print("Array 1-10:", array_a)
# b
array_b = np.arange(0.5, 5.25, 0.25)
print("Array 0.5 to 5.25:", array_b)

Array 1-10: [ 1  2  3  4  5  6  7  8  9 10]
Array 0.5 to 5.25: [0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75
 4.   4.25 4.5  4.75 5.  ]


In [3]:
# 2
# a
zeros_a = np.zeros(10)
print("Zeros array (10 elements):", zeros_a)
# b
zeros_b = np.zeros((4, 3))
print("Zeros array (4x3):")
print(zeros_b)

Zeros array (10 elements): [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Zeros array (4x3):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# 3
# a 
linspace_a = np.linspace(2, 12, 5)
print("Linspace array (2 to 12):", linspace_a)
# b
linspace_b = np.linspace(3, 9, 4)
print("Linspace array (3 to 9):", linspace_b)

Linspace array (2 to 12): [ 2.   4.5  7.   9.5 12. ]
Linspace array (3 to 9): [3. 5. 7. 9.]


In [7]:
# 4
# a
random_a = np.random.rand(4, 2)
print("Random array (4x2):")
print(random_a)

# b
random_b = np.random.randint(10, 21, (3, 3))
print("Random integer array (3x3):")
print(random_b)

reshaped_a = random_a.reshape(1, 8)
print("Reshaped array (1x8):")
print(reshaped_a)

Random array (4x2):
[[0.18274251 0.69355422]
 [0.11017427 0.14344126]
 [0.89891812 0.71488074]
 [0.99142372 0.53494605]]
Random integer array (3x3):
[[19 20 16]
 [20 20 11]
 [18 10 11]]
Reshaped array (1x8):
[[0.18274251 0.69355422 0.11017427 0.14344126 0.89891812 0.71488074
  0.99142372 0.53494605]]


In [9]:
# 5
np.random.seed(42)
seed_array = np.random.randint(0, 100, (3, 3))
print("Array with seed:")
print(seed_array)

# seed מאפשר שחזור תוצאות אקראיות 

Array with seed:
[[51 92 14]
 [71 60 20]
 [82 86 74]]


In [11]:
# 6
# a
user_list = [int(input("Enter a number: ")) for _ in range(5)]

# b
user_array = np.array(user_list)

# c
print("Maximum value:", user_array.max())

# d
print("Minimum value:", user_array.min())

# e
print("Array shape:", user_array.shape)

# f
print("Index of max value:", user_array.argmax())

# g
print("Index of min value:", user_array.argmin())


Enter a number:  25
Enter a number:  65
Enter a number:  95
Enter a number:  44
Enter a number:  85


Maximum value: 95
Minimum value: 25
Array shape: (5,)
Index of max value: 2
Index of min value: 0
